image: node:18

pipelines:
  default:
    - step:
        name: Run Playwright API Tests
        caches:
          - node
        script:
          - npm install
          - npx playwright install --with-deps
          - npx playwright test --reporter=dot,line,json,html
        artifacts:
          - playwright-report/**
